### ISSUE TITLE
Page-break-inline not working if we create table under tr tag. it is not break on page if table is not proper on page

### ISSUE THREAD

**Issue by kite57** [nreco/nreco#2]
Page-break-inline not working if we create table under tr tag. it is not break on page if table is not proper on page

Issue is in my html i have lots of table underling in tr tag and i am applying page-break-inline over table tag, still it is not working. my table is break on two page
It should be break if table height is long and table start from new page. although it is working if we use separate table html

**Comment by VitaliyMF** [comment]
@kite57 I suggest you're asking about NReco PdfGenerator (which is not actually a part of open source NReco framework). 

Page breaks doesn't work inside tables and if you need to specify page break explicitly you may split your table into 2 tables and paste <div/> with page-break-after css rule.
