### ISSUE TITLE
nReco is a thread Safe or Not ?

### ISSUE THREAD

**Issue by yashfale** [nreco/nreco#3]
Hi nReco Team, 
for testing purpose i am using nReco free version v2.0.50727, before i use this version production i want to know is nReco thread Safe ??

**Comment by VitaliyMF** [comment]
Hello @yashfale,

I assume that this is your question on SO: http://stackoverflow.com/questions/39793052/is-nreco-thread-safe-are-there-any-workaround-in-c-sharp/39804464  (I've provided an answer).

**Comment by yashfale** [comment]
Appreciate your response, we are using ThreadPool to process multiple PDFs in parallel and as you mentioned each of the object added to the Pool creates new instance of HTMLToPdfConverter class, but for some reason it fails to process in parallel. Do you think this is because we are using a Free-license version? Would we be able to achieve this if we go with a license version of NReco? Thanks

**Comment by VitaliyMF** [comment]
@yashfale again, I've answered in comment on SO :-)

Please note that support is not available for free PdfGenerator users.
